config/routes.rb
Rails.application.routes.draw do
root "pages#home"
get 'pages#home', to: 'pages#home'

resources :handcrafts do
    resources :comments, only: [:create]
end

get '/signup', to: 'artisans#new'
resources :artisans, except: [:new]

get '/login', to: 'sessions#new'
post '/login', to: "sessions#create"
delete '/logout', to: "sessions#destroy"

resources :materials, except: [:destroy]

end

app/models/handcraft.rb
class Handcraft < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 5, maximum: 800 }
    belongs_to :artisan
    validates :artisan_id, presence: true
    default_scope -> { order(updated_at: :desc) }
    has_many :handcraft_materials
    has_many :materials, through: :handcraft_materials
    has_many :comments, dependent: :destroy
end

app/controllers/handcrafts_controller.rb
class HandcraftsController < ApplicationController
    before_action :set_handcraft, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @handcrafts = Handcraft.paginate(page: params[:page], per_page: 5)
    end

    def show
        @comment = Comment.new
        @comments = @handcraft.comments.paginate(page: params[:page], per_page: 5)
    end

    def new
        @handcraft = Handcraft.new
    end

    def create
        @handcraft = Handcraft.new(handcraft_params)
        @handcraft.artisan = current_artisan
        if @handcraft.save
            flash[:success] = "O artesanato foi criado com sucesso!"
            redirect_to handcraft_path(@handcraft)
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def edit
        
    end
      
    def update
        if @handcraft.update(handcraft_params)
            flash[:success] = "O artesanato foi atualizado com sucesso!"
            redirect_to handcraft_path(@handcraft)
        else
          render 'edit'
        end
    end

      def destroy
        Handcraft.find(params[:id]).destroy
        flash[:success] = "O artesanato foi deletado com sucesso!"
        redirect_to handcrafts_path
      end

    private

        def set_handcraft
            @handcraft = Handcraft.find(params[:id])
        end

        def handcraft_params
            params.require(:handcraft).permit(:name, :description, material_ids: [])
        end

        def require_same_user
            if current_artisan != @handcraft.artisan and !current_artisan.admin?
              flash[:danger] = "Você só pode editar ou deletar os artesanatos criados por você"
              redirect_to handcrafts_path
            end  
        end
end

app/views/handcrafts/_form.html.erb
<%= render 'shared/errors', obj: @handcraft %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@handcraft, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name, "Nome" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Nome do artesanato", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description, "Descrição" %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control justify-text", placeholder: "Descreva sobre o artesanato" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <%= f.collection_check_boxes :material_ids, Material.all, :id, :name do |cb| %>
                    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                <% end %>
            </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@handcraft.new_record? ? "Criar meu artesanato" : "Atualizar meu artesanato", class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-6 col-md-offset-4 colormatch">
      [ <%= link_to "Cancelar a solicitação e retornar para a lista de artesanatos", handcrafts_path %> ]
    </div>
  </div>
</div>

app/views/handcrafts/_handcraft.html.erb
<% obj.each do |handcraft| %>
    <div class="row">
        <div class="col-md-2"> 
        <section class="artisan_info center">
            <%= gravatar_for(handcraft.artisan, size: 120) %>
        </section>
        </div>
        <div class="col-nd-8 well"> 
            <h4> <%= link_to handcraft.name, handcraft_path(handcraft) %> </h4>
            <p> <%= truncate(handcraft.description, length: 150) %> </p>
            <% if handcraft.materials.any? %>
                <p> Materiais: <%= render handcraft.materials %> </p>
            <% end%>
            <p>
            <span class="quiet"><small>Criado a <%= time_ago_in_words(handcraft.created_at) %> atrás por <%= handcraft.artisan.name.capitalize %>
                                                         | <%= pluralize(handcraft.comments.count, 'Commentário') %></small></span>
            </p>
            <% if logged_in? && (current_artisan == handcraft.artisan || current_artisan.admin?) %>
            <div class="handcraft-actions">
                <%= link_to "Edite este artesanato", edit_handcraft_path(handcraft), class: 'btn btn-xs btn-warning' %>
                <%= link_to "Delete este artesanato", handcraft_path(handcraft), method: :delete, data: { confirm: "Você tem certeza que quer deletar?" }, class: "btn btn-xs btn-danger" %>
            </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/handcrafts/edit.html.erb
<%= render 'shared/page_title', title: "Editar um Artesanato Existente" %>
<%= render 'form' %>

app/views/handcrafts/index.html.erb
<%= render 'shared/page_title', title: "Listagem de Todos os Artesanatos" %>

<div align="center">
<%= will_paginate %>
</div>
<%= render 'handcraft', obj: @handcrafts %>
<div align="center">
<%= will_paginate %>
</div>

app/views/handcrafts/new.html.erb
<%= render 'shared/page_title', title: "Criar um Novo Artesanato" %>
<%= render 'form' %>

app/views/handcrafts/show.html.erb
<%= render 'shared/page_title', title: @handcraft.name %>

<div class="well col-md-8 col-md-offset-2">
    <h4 class="center description"><strong> Descrição: </strong></h4>
    <hr />
    <div class="justify-text">
        <%= simple_format(@handcraft.description) %>
    </div>
    <hr />
    <% if @handcraft.materials.any? %>
        <p>Materiais: <%= render @handcraft.materials %></p>
    <% end %>
    <div class="pull-right">
        <p class="center">
            <em>Criado por:</em>
        </p>
        <p class="center">
            <%= link_to gravatar_for(@handcraft.artisan), artisan_path(@handcraft.artisan) %>
        </p>
        <p class="center">
            <small> <%= @handcraft.artisan.name.capitalize %></small>
            <div class="pull-right">
                <%= time_ago_in_words(@handcraft.created_at)%> atrás
            </div>
        </p>
    </div>
        <div class="handcraft-actions">
            <% if logged_in? && (current_artisan == @handcraft.artisan || current_artisan.admin? ) %>
                <%= link_to "Edite este artesanato", edit_handcraft_path(@handcraft), class: 'btn btn-xs btn-warning' %>
                <%= link_to "Delete este artesanato", handcraft_path(@handcraft), method: :delete, data: { confirm: "Você tem certeza que quer deletar?" }, class: "btn btn-xs btn-danger" %>
            <% end %>
            <%= link_to "Retorne para a listagem de artesanatos", handcrafts_path, class: 'btn btn-xs btn-primary' %>
        </div>     
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comentários: </h3>
      <hr />
      <%= form_for([@handcraft, @comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description, "Comentário" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 4, class: "form-control", placeholder: "Escreva o seu comentário aqui" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Enviar comentário", class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>
<% end %>

<% if @handcraft.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comentários: </h3>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Sem comentários</h3>
    </div>
  </div>
<% end %>