config/routes.rb
Rails.application.routes.draw do
root "pages#home"
get 'pages#home', to: 'pages#home'

resources :handcrafts do
    resources :comments, only: [:create]
end

get '/signup', to: 'artisans#new'
resources :artisans, except: [:new]

get '/login', to: 'sessions#new'
post '/login', to: "sessions#create"
delete '/logout', to: "sessions#destroy"

resources :materials, except: [:destroy]

end

app/models/material.rb
class Material < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :handcraft_materials
    has_many :handcrafts, through: :handcraft_materials
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
    before_action :set_material, only: [:edit, :update, :show]
    before_action :require_admin, except: [:show, :index]

    def new
        @material = Material.new
    end
    
    def create
        @material = Material.new(material_params)
        if @material.save
            flash[:success] = "O material foi criado com sucesso!"
            redirect_to material_path(@material)
        else
            render 'new', status: :unprocessable_entity
        end
    end
    
    def edit
      
    end
    
    def update
        if @material.update(material_params)
            flash[:success] = "O material foi atualizado com sucesso!"
            redirect_to @material
        else
            render 'edit'
        end      
    end
    
    def show
        @material_handcrafts = @material.handcrafts.paginate(page: params[:page], per_page: 5)
    end
    
    def index
      @materials = Material.paginate(page: params[:page], per_page: 5)
    end

    private

    def material_params
        params.require(:material).permit(:name)
    end

    def set_material
        @material = Material.find(params[:id])
    end

    def require_admin
        if !logged_in? || (logged_in? and !current_artisan.admin?)
          flash[:danger] = "Somente o administrador pode executar essa ação!"
          redirect_to materials_path
        end
    end
    
end

app/views/materials/_form.html.erb
<%= render 'shared/errors', obj: @material %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@material, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name, "Nome" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Nome do material", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@material.new_record? ? "Criar material" : "Atualizar material", class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-6 col-md-offset-4 colormatch">
      [ <%= link_to "Cancelar a solicitação e retornar para a lista de artesanatos", handcrafts_path %> ]
    </div>
  </div>
</div>

app/views/materials/_material.html.erb
<span class="badge"><%= link_to material.name, material_path(material) %> &nbsp; </span>

app/views/materials/edit.html.erb
<%= render 'shared/page_title', title: "Edite o Nome do Material" %>

<%= render 'form' %>

app/views/materials/index.html.erb
<%= render 'shared/page_title', title: "Listagem de Todos os Materiais" %>

<div align="center">
    <%= will_paginate %>
    <% @materials.each do |material| %>
    <ul class="listing">
    <div class="row">
        <div class="well col-md-4 col-md-offset-4">
            <li class="artisan-title"><%= link_to material.name.capitalize, material_path(material) %></li>
            <li><small><%= pluralize(material.handcrafts.count, "artesanato") if material.handcrafts %></small></li>
            <% if logged_in? && current_artisan.admin? %>
                <li><%= link_to "Edite este material", edit_material_path(material) %></li>
            <% end %>
        </div>
    </div>
    </ul>      
    <% end %>
    <%= will_paginate %>
</div>

app/views/materials/new.html.erb
<%= render 'shared/page_title', title: "Crie um Novo Material" %>

<%= render 'form' %>

app/views/materials/show.html.erb
<%= render 'shared/page_title', title: "#{@material.name}" %>

<% if @material.handcrafts.count != 0 %>
    <h4 align="center"> Artesanatos que utilizam <%= @material.name %> </h4>
    <div align="center">
    <%= will_paginate @material_handcrafts %>
    </div>
    <%= render 'handcrafts/handcraft', obj: @material_handcrafts %>
    <div align="center">
    <%= will_paginate @material_handcrafts %>
<% else %>
    <h4 align="center"> O material não tem artesanatos cadastrados </h4>
<% end %>
</div>