config/routes.rb
Rails.application.routes.draw do
root "pages#home"
get 'pages#home', to: 'pages#home'

resources :handcrafts do
    resources :comments, only: [:create]
end

get '/signup', to: 'artisans#new'
resources :artisans, except: [:new]

get '/login', to: 'sessions#new'
post '/login', to: "sessions#create"
delete '/logout', to: "sessions#destroy"

resources :materials, except: [:destroy]

end

app/views/layouts/_footer.html.erb
<!-- Site footer -->
    <footer class="footer">
    <small>
    <strong> <a href= "http://www.cursodeartesanato.com"> Artesanato em Geral </a></strong>
    por <em> <a href= "http://www.cursodeartesanato.com" > Vanessa Souza</a> </em>
    </small> 

    <nav>
    <ul>
        <li> <%= link_to "Sobre", "#" %></li>
    </ul>
    </nav>
    </footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Meus Artesanatos", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="links"><%= link_to "Lista de Artesãos", artisans_path %></li>
        <li class="links"><%= link_to "Lista de Artesanatos", handcrafts_path %></li>
        <% if logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="links">Artesanatos <span class="caret"></span> </span></a>
            <ul class="dropdown-menu">
                <li><%= link_to "Criar novo artesanato", new_handcraft_path %></li>
            </ul>
            </li>
        <% end %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="links">Materiais <span class="caret"></span> </span></a>
                <ul class="dropdown-menu">
                <li><%= link_to "Todos os materiais", materials_path %></li>
                <% Material.all.each do |material| %>
                    <li><%= link_to material.name.capitalize, material_path(material) %> </li>
                <% end %>
                <% if logged_in? && current_artisan.admin? %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Criar Novo Material", new_material_path %></li>
                <% end %>    
                </ul>
            </li>    
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="O que você procura?">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
      <ul class="nav navbar-nav navbar-right">    
        <% if logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="links">Perfil de <%= current_artisan.name.capitalize %> <%= "Admin" if current_artisan.admin? %> <span class="caret"></span> </span></a>
            <ul class="dropdown-menu">
                <li><%= link_to "Veja seu perfil", artisan_path(current_artisan) %></li>
                <li><%= link_to "Edite seu Perfil", edit_artisan_path(current_artisan) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
            </li>
        <% else %>
            <li class="links"><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>blogdeartesanato</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class= "container">
    <%= yield %>    
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>